# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'update-search-index'

inputs:
  GITHUB_TOKEN:
    required: true
  ALGOLIA_ID:
    required: true
  ALGOLIA_KEY:
    required: true
  ALGOLIA_INDEX:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ./action/node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: Install
      run: yarn
      working-directory: ./packages/action

    # FIXME: 마지막 sha 기준으로 빌드 확인하도록 변경하기
    # - name: Cache build file
    #   uses: actions/cache@v2
    #   id: cache_dist
    #   with:
    #     path: dist
    #     key: ${{ runner.os }}-dist-${{ hashFiles('**/index.js') }}
    #     restore-keys: ${{ runner.os }}-dist-

    - name: Build
      if: steps.cache_dist.outputs.cache-hit != 'true'
      run: yarn build
      working-directory: ./packages/action

    - name: Execute
      run: yarn start
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ALGOLIA_ID: ${{ inputs.ALGOLIA_ID }}
        ALGOLIA_KEY: ${{ inputs.ALGOLIA_KEY }}
        ALGOLIA_INDEX: ${{ inputs.ALGOLIA_INDEX }}
      working-directory: ./packages/action
